version: '3.8'

services:
  recipe-bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./recipe_data:/app/recipe_data
    restart: unless-stopped
